"""add_farm_name_field
Revision ID: 218be56aa5e5
Revises: 37165b0ce9c6
Create Date: 2025-11-18 17:50:45.815432

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
import sqlmodel 

# revision identifiers, used by Alembic.
revision: str = '218be56aa5e5'
down_revision: Union[str, Sequence[str], None] = '37165b0ce9c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('farms', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###
def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('farms', 'name')
    # ### end Alembic commands ###
