"""add farms table
Revision ID: 37165b0ce9c6
Revises: 66f3210f6a14
Create Date: 2025-11-16 16:58:05.580056

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
import sqlmodel 
from sqlalchemy.dialects import postgresql
# revision identifiers, used by Alembic.
revision: str = '37165b0ce9c6'
down_revision: Union[str, Sequence[str], None] = '66f3210f6a14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('farms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('crop', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_farms_user_id'), 'farms', ['user_id'], unique=False)
    # ### end Alembic commands ###
def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_farms_user_id'), table_name='farms')
    op.drop_table('farms')
    # ### end Alembic commands ###
