"""add scans table
Revision ID: 55ef5a97c2f3
Revises: 8e57de9c2c09
Create Date: 2025-11-11 16:41:19.480245

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
import sqlmodel 

# revision identifiers, used by Alembic.
revision: str = '55ef5a97c2f3'
down_revision: Union[str, Sequence[str], None] = '8e57de9c2c09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
