"""add weather tables
Revision ID: 66f3210f6a14
Revises: 97f41d1bb75c
Create Date: 2025-11-16 16:14:27.114168

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
import sqlmodel 

# revision identifiers, used by Alembic.
revision: str = '66f3210f6a14'
down_revision: Union[str, Sequence[str], None] = '97f41d1bb75c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
