"""add weather tables
Revision ID: 97f41d1bb75c
Revises: 5e57e2551f1f
Create Date: 2025-11-16 16:14:07.813784

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
import sqlmodel 

# revision identifiers, used by Alembic.
revision: str = '97f41d1bb75c'
down_revision: Union[str, Sequence[str], None] = '5e57e2551f1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
